<?php
define("MENU_TXT_FAQ","FAQ"); 
define("MENU_TXT_LOGIN_CUSTOMER","Customer Login"); 
define("MENU_TXT_LOGIN_EMPLOYEE","Employee Login"); 
define("INDEX_TITLE", "Welcome to Space Pirate Helpdesk");
define("INDEX_SUBHEADING", "The title should be renamed to and this subheading include a witty tagline.");
define("LOGIN_SIGN_IN", "Please log in");
define("LOGIN_USERNAME", "Email address");
define("LOGIN_PASSWORD", "Password");
define("LOGIN_BUTTON_SIGNIN", "Sign in");