# Dockerfile.dojo-basic
FROM php:7.4.27-apache-bullseye

RUN docker-php-ext-install pdo_mysql mysqli
RUN apt-get update && apt-get install -y dnsutils
COPY ./src/basic /var/www/html
LABEL org.opencontainers.image.source=https://github.com/SamuraiWTF/samurai-dojo
LABEL org.opencontainers.image.description="Basic PHP 7.4.27-apache-bullseye image with dojo-basic and mysql support."
LABEL org.opencontainers.image.licenses="lgpl"